slam_toolbox:
  ros__parameters:
    # Frames
    map_frame: map
    odom_frame: odom
    base_frame: base_link

    # Topic
    scan_topic: /scan

    # Timing
    use_sim_time: true

    # SLAM mode
    mode: mapping

    # Performance (good results)
    resolution: 0.05
    max_laser_range: 10.0
    minimum_time_intervel: 0.2
    transform_timeout: 0.5
    tf_buffer_duration: 30.0
    scan_queue_size: 50

    # Map update
    update_map_every_scan: true

    # Loop closure
    do_loop_closing: true
    loop_search_maximum_distance: 3.0
